version: '3.8'

services:

  application-blocking-platform-thread:
    image: wdotto/application-blocking-thread
    container_name: application-blocking-thread
    build: 
       context: ./spring-boot-3-java-17-platform-thread
       dockerfile: Dockerfile
    ports:
      - "8089:8089"

  application-async-platform-threads:
    image: wdotto/application-platform-thread
    container_name: application-platform-thread
    build: 
       context: ./spring-boot-3-java-17-async-platform-threads
       dockerfile: Dockerfile
    ports:
      - "8090:8090"

  application-virtual-thread:
    image: wdotto/application-virtual-thread
    container_name: application-virtual-thread
    build: 
       context: ./spring-boot-3-java-21-virtual-thread
       dockerfile: Dockerfile
    ports:
      - "8091:8091"